# Site settings
title: Luster
email: nidev@mrn.org
description: >
  Styles for COINS web applications.

# Server
baseurl: ""
url: "https://mrn-code.github.io/"
encoding: UTF-8

# Build settings
source: docs
destination: _gh_pages

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
